samples:
  sample-barcode05: /mnt/c/Users/filip/OneDrive/Desktop/pipelines/development_assets/ViralIUnity_test_data/nanopore_data/nanopore/barcode05.fastq
  sample-barcode09: /mnt/c/Users/filip/OneDrive/Desktop/pipelines/development_assets/ViralIUnity_test_data/nanopore_data/nanopore/barcode09.fastq
data: nanopore
output: output/meta_nanopore_v1/
threads: 2
kraken2_database: /mnt/c/Users/filip/OneDrive/Desktop/pipelines/development_assets/kraken2_databases/viral/
krona_database: /home/fmoreira/miniforge3/envs/viralunity/opt/krona/taxonomy/
remove_human_reads: false
remove_unclassified_reads: false
